/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: e6ZxPuHCfPgHyJvfyLEMAD
import { createUseGlobalVariants } from "@plasmicapp/react-web";
import { useScreenVariants as useScreenVariantsn2MwlGajyZj } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: n2MWL_GAJYZj/globalVariant
import { useLocale } from "./PlasmicGlobalVariant__Locale"; // plasmic-import: uH-Kq1IL8lzA/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsn2MwlGajyZj,
  locale: useLocale
});
