/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: e6ZxPuHCfPgHyJvfyLEMAD
import { createUseStyleTokens } from "@plasmicapp/react-web";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: e6ZxPuHCfPgHyJvfyLEMAD/projectModule
import "./plasmic.css"; // plasmic-import: e6ZxPuHCfPgHyJvfyLEMAD/projectcss

const data = {
  base: `${"plasmic_tokens_e6ZxPuHCfPgHyJvfyLEMAD"}`,
  varianted: []
};

export const _useStyleTokens = createUseStyleTokens(data, _useGlobalVariants);
